typography_spectrum: 1
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.99239805736579
  lightness: 0.9514616385567933
  saturation: 0.05919963726773858
  rhythmicContrast: 0.8230203760322183
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.32098117657005787
analytics:
  google: null
  facebook: null
  twitter: null
name: valeriospinaci
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Valerio Spinaci P.A.
description: International Law Firm
purpose: []
